/**
 * Maps API profile / server JSON into flat string fields used by ProfileBuilder.
 */
export function profileToInitialValues(p: { id?: number; [key: string]: unknown }): Record<string, string> {
  const pc = (p.preferred_courses as string[]) ?? [];
  return {
    full_name: String(p.full_name ?? ""),
    email: String(p.email ?? ""),
    age: p.age != null ? String(p.age) : "",
    gender: String(p.gender ?? ""),
    region: String(p.region ?? ""),
    province: String(p.province ?? ""),
    city_municipality: String(p.city_municipality ?? ""),
    barangay: String(p.barangay ?? ""),
    school: String(p.school ?? ""),
    school_type: String(p.school_type ?? ""),
    target_school: String(p.target_school ?? ""),
    education_level: String(p.education_level ?? ""),
    enrollment_status: String(p.enrollment_status ?? ""),
    current_year_level: p.current_year_level != null ? String(p.current_year_level) : "",
    current_academic_stage: String(p.current_academic_stage ?? ""),
    target_academic_year: String(p.target_academic_year ?? ""),
    field_of_study_broad: String(p.field_of_study_broad ?? ""),
    field_of_study_specific: String(p.field_of_study_specific ?? ""),
    preferred_course_1: pc[0] ?? "",
    preferred_course_2: pc[1] ?? "",
    preferred_course_3: pc[2] ?? "",
    gwa_raw: String(p.gwa_raw ?? ""),
    gwa_scale: String(p.gwa_scale ?? ""),
    needs: Array.isArray(p.needs) ? p.needs.join(", ") : "",
    extracurriculars: Array.isArray(p.extracurriculars) ? p.extracurriculars.join(", ") : "",
    awards: Array.isArray(p.awards) ? p.awards.join(", ") : "",
    household_income_annual: p.household_income_annual != null ? String(p.household_income_annual) : "",
    income_bracket: String(p.income_bracket ?? ""),
    parent_occupation: String(p.parent_occupation ?? ""),
    is_underprivileged: (p as { is_underprivileged?: boolean }).is_underprivileged ? "on" : "",
    is_pwd: (p as { is_pwd?: boolean }).is_pwd ? "on" : "",
    is_indigenous_people: (p as { is_indigenous_people?: boolean }).is_indigenous_people ? "on" : "",
    is_solo_parent_dependent: (p as { is_solo_parent_dependent?: boolean }).is_solo_parent_dependent ? "on" : "",
    is_ofw_dependent: (p as { is_ofw_dependent?: boolean }).is_ofw_dependent ? "on" : "",
    is_farmer_fisher_dependent: (p as { is_farmer_fisher_dependent?: boolean }).is_farmer_fisher_dependent ? "on" : "",
    is_4ps_listahanan: (p as { is_4ps_listahanan?: boolean }).is_4ps_listahanan ? "on" : "",
    is_military_dependent: (p as { is_military_dependent?: boolean }).is_military_dependent ? "on" : "",
    is_uniformed_service_dependent: (p as { is_uniformed_service_dependent?: boolean }).is_uniformed_service_dependent ? "on" : "",
    is_gsis_dependent: (p as { is_gsis_dependent?: boolean }).is_gsis_dependent ? "on" : "",
    is_sss_dependent: (p as { is_sss_dependent?: boolean }).is_sss_dependent ? "on" : "",
    employment_status: String((p as { employment_status?: string }).employment_status ?? ""),
    evening_weekend_program: (p as { evening_weekend_program?: boolean }).evening_weekend_program ? "on" : "",
    athlete_level: String((p as { athlete_level?: string }).athlete_level ?? ""),
    privacy_consent: (p as { privacy_consent?: boolean }).privacy_consent ? "on" : "",
  };
}
