"""
Add B5 persona batch (PR-03…PR-41 minus already-shipped) and field fixtures.

Usage:
  python -m app.scripts.add_b5_personas
  python -m app.scripts.regenerate_persona_goldens --write-catalog
"""

from __future__ import annotations

import json
from copy import deepcopy
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
CATALOG_PATH = REPO / "app" / "tests" / "fixtures" / "persona_catalog.json"

NEW_SCHOLARSHIPS = [
    {
        "id": 151,
        "title": "Engineering Field Grant",
        "provider": "Fixture",
        "link": "https://example.com/fixture/151",
        "description": "Engineering PSCED restriction",
        "eligible_levels": ["College"],
        "eligible_regions": [],
        "eligible_courses_psced": ["Engineering"],
        "is_active": True,
        "data_status": "active",
        "application_status": "open",
    },
    {
        "id": 152,
        "title": "Communication Field Grant",
        "provider": "Fixture",
        "link": "https://example.com/fixture/152",
        "description": "Communication sub-discipline restriction",
        "eligible_levels": ["College"],
        "eligible_regions": [],
        "eligible_courses_psced": ["Communication"],
        "is_active": True,
        "data_status": "active",
        "application_status": "open",
    },
    {
        "id": 153,
        "title": "Medical Health Grant",
        "provider": "Fixture",
        "link": "https://example.com/fixture/153",
        "description": "Medical broad restriction",
        "eligible_levels": ["College"],
        "eligible_regions": [],
        "eligible_courses_psced": ["Medical"],
        "is_active": True,
        "data_status": "active",
        "application_status": "open",
    },
    {
        "id": 154,
        "title": "Agriculture Rural Grant",
        "provider": "Fixture",
        "link": "https://example.com/fixture/154",
        "description": "Agriculture broad restriction",
        "eligible_levels": ["College"],
        "eligible_regions": [],
        "eligible_courses_psced": ["Agriculture"],
        "is_active": True,
        "data_status": "active",
        "application_status": "open",
    },
    {
        "id": 155,
        "title": "Arts Humanities Grant",
        "provider": "Fixture",
        "link": "https://example.com/fixture/155",
        "description": "Arts broad restriction",
        "eligible_levels": ["College"],
        "eligible_regions": [],
        "eligible_courses_psced": ["Arts"],
        "is_active": True,
        "data_status": "active",
        "application_status": "open",
    },
    {
        "id": 156,
        "title": "CALABARZON Regional",
        "provider": "Fixture",
        "link": "https://example.com/fixture/156",
        "description": "Region IV-A only",
        "eligible_levels": ["College"],
        "eligible_regions": ["Region IV-A - CALABARZON"],
        "is_active": True,
        "data_status": "active",
        "application_status": "open",
    },
    {
        "id": 157,
        "title": "Athletic Merit Grant",
        "provider": "Fixture",
        "link": "https://example.com/fixture/157",
        "description": "Merit for student athletes (talent)",
        "eligible_levels": ["College"],
        "eligible_regions": [],
        "scholarship_type": "Merit-based",
        "min_gwa_normalized": 75,
        "is_active": True,
        "data_status": "active",
        "application_status": "open",
    },
    {
        "id": 158,
        "title": "Incoming Freshman Only",
        "provider": "Fixture",
        "link": "https://example.com/fixture/158",
        "description": "First-year college entrants",
        "eligible_levels": ["College"],
        "eligible_regions": [],
        "eligible_year_levels": [1],
        "is_active": True,
        "data_status": "active",
        "application_status": "open",
    },
    {
        "id": 159,
        "title": "Nursing Specific Course",
        "provider": "Fixture",
        "link": "https://example.com/fixture/159",
        "description": "BS Nursing specific",
        "eligible_levels": ["College"],
        "eligible_regions": [],
        "eligible_courses_specific": ["BS Nursing"],
        "is_active": True,
        "data_status": "active",
        "application_status": "open",
    },
    {
        "id": 160,
        "title": "Region II Cagayan Valley",
        "provider": "Fixture",
        "link": "https://example.com/fixture/160",
        "description": "Region II geographic grant",
        "eligible_levels": ["College"],
        "eligible_regions": ["Region II - Cagayan Valley"],
        "is_active": True,
        "data_status": "active",
        "application_status": "open",
    },
]

NEW_PERSONAS = [
    {
        "id": "ana_accountancy_2nd_year",
        "pr_ids": ["PR-03"],
        "label": "Ana — 2nd year accountancy, private NCR, 5.0-scale GWA",
        "profile": {
            "age": 19,
            "education_level": "College",
            "current_year_level": 2,
            "region": "National Capital Region",
            "city_municipality": "Manila",
            "school_type": "Private",
            "household_income_annual": 325000,
            "gwa_normalized": 93.75,
            "field_of_study_broad": "Accountancy",
            "preferred_courses": ["BS Accountancy"],
        },
        "must_include": [120, 121, 125, 112],
        "must_exclude": [103, 116],
        "notes": "5.0-scale 1.75 equivalent; need 250k excluded; public-only excluded",
    },
    {
        "id": "miguel_graduating_civil",
        "pr_ids": ["PR-04"],
        "label": "Miguel — graduating civil engineering, Region VII",
        "profile": {
            "age": 21,
            "education_level": "College",
            "current_year_level": 4,
            "enrollment_status": "graduating",
            "region": "Region VII - Central Visayas",
            "city_municipality": "Cebu City",
            "school_type": "Public",
            "household_income_annual": 320000,
            "gwa_normalized": 85,
            "field_of_study_broad": "Civil Engineering",
            "preferred_courses": [],
        },
        "must_include": [101, 151],
        "must_exclude": [158],
        "notes": "Engineering matches STEM via hierarchy; incoming-freshman-only excluded",
    },
    {
        "id": "grace_graduate_ms",
        "pr_ids": ["PR-05"],
        "label": "Grace — graduate MS Biology, NCR",
        "profile": {
            "age": 24,
            "education_level": "Graduate",
            "region": "National Capital Region",
            "school_type": "Public",
            "household_income_annual": 450000,
            "gwa_normalized": 88,
            "field_of_study_broad": "Biology",
            "preferred_courses": [],
        },
        "must_include": [144],
        "must_exclude": [101, 105],
        "notes": "Graduate-only vs undergraduate/SHS fixtures",
    },
    {
        "id": "ben_tvet_welding",
        "pr_ids": ["PR-06"],
        "label": "Ben — TVET welding trainee, Region XII",
        "profile": {
            "age": 18,
            "education_level": "TVET",
            "current_academic_stage": "TVET",
            "region": "Region XII - SOCCSKSARGEN",
            "school_type": "Public",
            "household_income_annual": 120000,
            "field_of_study_broad": "Shielded Metal Arc Welding NC II",
            "preferred_courses": [],
        },
        "must_include": [143],
        "must_exclude": [101, 104],
        "notes": "TVET path; college GWA-gated merit excluded",
    },
    {
        "id": "carlo_transferee_it",
        "pr_ids": ["PR-08"],
        "label": "Carlo — transferee 3rd year IT, CALABARZON",
        "profile": {
            "age": 20,
            "education_level": "College",
            "current_year_level": 3,
            "enrollment_status": "transferee",
            "region": "Region IV-A - CALABARZON",
            "city_municipality": "Los Baños",
            "school_type": "Private",
            "household_income_annual": 330000,
            "gwa_normalized": 81.25,
            "field_of_study_broad": "Information Technology",
            "preferred_courses": [],
        },
        "must_include": [101, 141, 156],
        "must_exclude": [103],
        "notes": "Transferee-only fixture included; 5.0-scale 2.25 normalized",
    },
    {
        "id": "paolo_middle_income",
        "pr_ids": ["PR-10"],
        "label": "Paolo — middle income marketing student, NCR private",
        "profile": {
            "age": 20,
            "education_level": "College",
            "region": "National Capital Region",
            "school_type": "Private",
            "household_income_annual": 380000,
            "gwa_normalized": 89,
            "field_of_study_broad": "Marketing Management",
            "preferred_courses": [],
        },
        "must_include": [125, 112, 120],
        "must_exclude": [103],
        "notes": "380k above 250k need ceiling; 400k ceiling grants OK",
    },
    {
        "id": "high_gwa_mathematics",
        "pr_ids": ["PR-13"],
        "label": "High GWA mathematics, low income, Region II",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "Region II - Cagayan Valley",
            "school_type": "Public",
            "household_income_annual": 180000,
            "gwa_normalized": 96,
            "field_of_study_broad": "Mathematics",
            "preferred_courses": [],
        },
        "must_include": [101, 103, 104, 160],
        "must_exclude": [],
        "notes": "Near-max academic and need components; regional fixture",
    },
    {
        "id": "gwa_scale_parity",
        "pr_ids": ["PR-15"],
        "label": "GWA scale parity anchor (percentage baseline)",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "National Capital Region",
            "school_type": "Public",
            "household_income_annual": 200000,
            "gwa_normalized": 88,
            "field_of_study_broad": "STEM",
            "preferred_courses": [],
        },
        "must_include": [101, 122],
        "must_exclude": [104],
        "notes": "PR-15 also guarded by test_pr15_gwa_scale_equivalence",
    },
    {
        "id": "public_university_student",
        "pr_ids": ["PR-17"],
        "label": "Public university student",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "National Capital Region",
            "school_type": "Public",
            "household_income_annual": 200000,
            "gwa_normalized": 88,
            "field_of_study_broad": "STEM",
            "preferred_courses": [],
        },
        "must_include": [116, 101],
        "must_exclude": [117],
        "notes": "Public-only vs private-only school type gates",
    },
    {
        "id": "up_diliman_named_school",
        "pr_ids": ["PR-19"],
        "label": "UP Diliman named-school match",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "National Capital Region",
            "school_type": "Public",
            "school": "UP Diliman",
            "school_id": "university-of-the-philippines-diliman",
            "household_income_annual": 250000,
            "gwa_normalized": 92,
            "field_of_study_broad": "STEM",
            "preferred_courses": [],
        },
        "must_include": [118, 119],
        "must_exclude": [],
        "notes": "Named school and UP system registry normalization",
    },
    {
        "id": "suc_category_student",
        "pr_ids": ["PR-20"],
        "label": "SUC category student",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "Region III - Central Luzon",
            "school_type": "Public",
            "school": "PUP",
            "school_id": "polytechnic-university-of-the-philippines",
            "household_income_annual": 200000,
            "gwa_normalized": 87,
            "field_of_study_broad": "STEM",
            "preferred_courses": [],
        },
        "must_include": [146],
        "must_exclude": [117],
        "notes": "SUC category gate via school registry",
    },
    {
        "id": "mindanao_davao",
        "pr_ids": ["PR-22"],
        "label": "Mindanao Davao Region XI resident",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "Region XI - Davao Region",
            "school_type": "Public",
            "household_income_annual": 200000,
            "gwa_normalized": 88,
            "field_of_study_broad": "STEM",
            "preferred_courses": [],
        },
        "must_include": [147, 101],
        "must_exclude": [114],
        "notes": "Davao regional vs BARMM-only exclusion",
    },
    {
        "id": "barmm_resident",
        "pr_ids": ["PR-23"],
        "label": "BARMM resident",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "BARMM",
            "school_type": "Public",
            "household_income_annual": 150000,
            "gwa_normalized": 86,
            "field_of_study_broad": "Education",
            "preferred_courses": [],
        },
        "must_include": [114],
        "must_exclude": [147],
        "notes": "BARMM alias handling",
    },
    {
        "id": "calabarzon_alias",
        "pr_ids": ["PR-24"],
        "label": "CALABARZON region alias student",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "CALABARZON",
            "school_type": "Public",
            "household_income_annual": 200000,
            "gwa_normalized": 88,
            "field_of_study_broad": "STEM",
            "preferred_courses": [],
        },
        "must_include": [156, 101],
        "must_exclude": [102],
        "notes": "Region alias robustness; detailed alias variants in test_pr24_region_aliases",
    },
    {
        "id": "engineering_student",
        "pr_ids": ["PR-25"],
        "label": "Civil engineering vs field restrictions",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "National Capital Region",
            "school_type": "Public",
            "household_income_annual": 220000,
            "gwa_normalized": 90,
            "field_of_study_broad": "Civil Engineering",
            "preferred_courses": [],
        },
        "must_include": [101, 151],
        "must_exclude": [120],
        "notes": "Engineering + STEM hierarchy; business-only excluded",
    },
    {
        "id": "devcom_student",
        "pr_ids": ["PR-26"],
        "label": "Development Communication — taxonomy before/after proof",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "National Capital Region",
            "school_type": "Public",
            "household_income_annual": 200000,
            "gwa_normalized": 88,
            "field_of_study_broad": "Development Communication",
            "preferred_courses": ["BA Development Communication"],
        },
        "must_include": [155, 152, 103],
        "must_exclude": [101],
        "notes": "DevCom matches Communication and Arts ancestors; STEM-only excluded",
    },
    {
        "id": "nursing_student",
        "pr_ids": ["PR-27"],
        "label": "BS Nursing health sciences",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "National Capital Region",
            "school_type": "Public",
            "household_income_annual": 200000,
            "gwa_normalized": 90,
            "field_of_study_broad": "Nursing",
            "preferred_courses": ["BS Nursing"],
        },
        "must_include": [153, 159, 103],
        "must_exclude": [151],
        "notes": "Medical broad + nursing specific; engineering excluded",
    },
    {
        "id": "agriculture_student",
        "pr_ids": ["PR-28"],
        "label": "Agriculture student, Region II",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "Region II - Cagayan Valley",
            "school_type": "Public",
            "household_income_annual": 180000,
            "gwa_normalized": 87,
            "field_of_study_broad": "Agriculture",
            "preferred_courses": [],
        },
        "must_include": [154, 160],
        "must_exclude": [101],
        "notes": "Agriculture-restricted + regional overlap",
    },
    {
        "id": "arts_literature",
        "pr_ids": ["PR-30"],
        "label": "BA Literature arts and humanities",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "National Capital Region",
            "school_type": "Public",
            "household_income_annual": 200000,
            "gwa_normalized": 88,
            "field_of_study_broad": "Literature",
            "preferred_courses": ["BA Literature"],
        },
        "must_include": [155, 103],
        "must_exclude": [101],
        "notes": "Arts broad; must not over-match STEM-restricted fixtures",
    },
    {
        "id": "pwd_priority_student",
        "pr_ids": ["PR-31"],
        "label": "PWD priority equity student",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "Region III - Central Luzon",
            "school_type": "Public",
            "household_income_annual": 180000,
            "gwa_normalized": 88,
            "field_of_study_broad": "STEM",
            "is_pwd": True,
            "preferred_courses": [],
        },
        "must_include": [127, 103],
        "must_exclude": [],
        "notes": "PWD-priority fixture; equity component ranking invariant",
        "ranking_invariants": [{"above": 127, "below": 103}],
    },
    {
        "id": "ip_priority_student",
        "pr_ids": ["PR-32"],
        "label": "Indigenous Peoples priority, Region XI",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "Region XI - Davao Region",
            "school_type": "Public",
            "household_income_annual": 150000,
            "gwa_normalized": 86,
            "field_of_study_broad": "Education",
            "is_indigenous_people": True,
            "preferred_courses": [],
        },
        "must_include": [128, 147],
        "must_exclude": [],
        "notes": "IP priority + Mindanao regional",
    },
    {
        "id": "solo_parent_dependent",
        "pr_ids": ["PR-33"],
        "label": "Solo-parent dependent, NCR",
        "profile": {
            "age": 18,
            "education_level": "College",
            "region": "National Capital Region",
            "school_type": "Public",
            "household_income_annual": 180000,
            "gwa_normalized": 87,
            "field_of_study_broad": "STEM",
            "is_solo_parent_dependent": True,
            "preferred_courses": [],
        },
        "must_include": [129, 103],
        "must_exclude": [],
        "notes": "Solo-parent priority (RA 11861)",
    },
    {
        "id": "student_athlete",
        "pr_ids": ["PR-35"],
        "label": "Varsity athlete — athlete flag gap documented",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "National Capital Region",
            "school_type": "Private",
            "household_income_annual": 400000,
            "gwa_normalized": 80,
            "field_of_study_broad": "Sports Science",
            "preferred_courses": [],
        },
        "must_include": [157],
        "must_exclude": [103],
        "notes": "Athlete level not first-class yet (DATA-08); merit athletic fixture",
    },
    {
        "id": "ofw_dependent",
        "pr_ids": ["PR-36"],
        "label": "OFW dependent priority",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "National Capital Region",
            "school_type": "Public",
            "household_income_annual": 200000,
            "gwa_normalized": 88,
            "field_of_study_broad": "STEM",
            "is_ofw_dependent": True,
            "preferred_courses": [],
        },
        "must_include": [130, 103],
        "must_exclude": [],
        "notes": "OFW-priority fixture",
    },
    {
        "id": "farmer_fisher_dependent",
        "pr_ids": ["PR-37"],
        "label": "Farmer/fisher dependent, Region VI",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "Region VI - Western Visayas",
            "school_type": "Public",
            "household_income_annual": 160000,
            "gwa_normalized": 86,
            "field_of_study_broad": "Agriculture",
            "is_farmer_fisher_dependent": True,
            "preferred_courses": [],
        },
        "must_include": [131, 102, 154],
        "must_exclude": [],
        "notes": "Agricultural-family priority + Visayas regional",
    },
    {
        "id": "gsis_dependent_member",
        "pr_ids": ["PR-38"],
        "label": "GSIS members-only dependent",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "National Capital Region",
            "school_type": "Public",
            "household_income_annual": 300000,
            "gwa_normalized": 88,
            "field_of_study_broad": "STEM",
            "is_gsis_dependent": True,
            "preferred_courses": [],
        },
        "must_include": [136],
        "must_exclude": [137],
        "notes": "GSIS members-only vs SSS-only",
    },
    {
        "id": "passed_deadline_visible",
        "pr_ids": ["PR-39"],
        "label": "Passed-deadline row remains visible, sorted last",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "National Capital Region",
            "school_type": "Public",
            "household_income_annual": 200000,
            "gwa_normalized": 90,
            "field_of_study_broad": "STEM",
            "preferred_courses": [],
        },
        "must_include": [142, 101],
        "must_exclude": [],
        "notes": "142 returned with deadline_passed; sorted below open rows",
        "ranking_invariants": [{"above": 101, "below": 142}],
    },
    {
        "id": "needs_review_penalty",
        "pr_ids": ["PR-40"],
        "label": "needs_review data_status scoring penalty",
        "profile": {
            "age": 19,
            "education_level": "College",
            "region": "National Capital Region",
            "school_type": "Public",
            "household_income_annual": 200000,
            "gwa_normalized": 90,
            "field_of_study_broad": "STEM",
            "preferred_courses": [],
        },
        "must_include": [101, 111],
        "must_exclude": [],
        "notes": "111 (needs_review) scores lower than clean 101",
        "ranking_invariants": [{"above": 101, "below": 111}],
    },
    {
        "id": "over_constrained_near_miss",
        "pr_ids": ["PR-41"],
        "label": "Over-constrained profile still gets near-miss explanations",
        "profile": {
            "age": 30,
            "education_level": "College",
            "region": "BARMM",
            "school_type": "Private",
            "household_income_annual": 900000,
            "gwa_normalized": 70,
            "field_of_study_broad": "Law",
            "preferred_courses": [],
        },
        "must_include": [],
        "must_exclude": [103],
        "notes": "Never an unexplained empty list — near-misses with reasons",
    },
]


def main() -> None:
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    existing_ids = {s["id"] for s in catalog["scholarships"]}
    for sch in NEW_SCHOLARSHIPS:
        if sch["id"] not in existing_ids:
            catalog["scholarships"].append(sch)

    existing_slugs = {p["id"] for p in catalog["personas"]}
    existing_prs = {pr for p in catalog["personas"] for pr in p.get("pr_ids", [])}

    added = 0
    for persona in NEW_PERSONAS:
        pr = persona["pr_ids"][0]
        if pr in existing_prs:
            continue
        if persona["id"] in existing_slugs:
            continue
        catalog["personas"].append(deepcopy(persona))
        added += 1

    CATALOG_PATH.write_text(json.dumps(catalog, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Added {added} personas; catalog now has {len(catalog['personas'])} personas, {len(catalog['scholarships'])} scholarships")


if __name__ == "__main__":
    main()
